title: 'shefbots.github.io'
description: "ShefBots"
baseurl: "/"
url: "https://shefbots.github.io"

header_pages:
  - index.md
  - members.md
  - support.md
  - rss.md

style: dark
listen_for_clients_preferred_style: false

author: Fred

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

banner: '<p class="centr"><a href="/"><img src="https://shefbots.github.io/assets/shefbots_logo.png" alt="ShefBots Logo" /></a></p>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-feed
