title: 'shefbots.github.io'
description: "ShefBots"
baseurl: "/"
url: "https://shefbots.github.io"

header_pages:
  - index.md
#  - members.md

style: dark

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

banner: |
  ![ShefBots Logo]({{ site.url }}/assets/shefbots_logo.png)
  {: style="text-align: center;"}

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
