title: 'shefbots.github.io'
description: "ShefBots"
baseurl: "/"
url: "https://shefbots.github.io"

header_pages:
  - index.md
#  - members.md

style: dark

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# this is markdownified
banner: <p style="text-align: center;"><img src="https://shefbots.github.io/assets/shefbots_logo.png" alt="ShefBots Logo" /></p>

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
